### PR TITLE
Add UR crypto-psbt specification

### PR DESCRIPTION
**Pull request by craigraw**
As PSBT is a self describing binary format, this specification uses only a CBOR byte string to represent the binary PSBT data.

The UR type is however useful in distinguishing it from other binary data.

### CODE REVIEW

**Review by ChristopherA — COMMENTED** [review]
Thank you for sharing this PR!

I'd ideally like to get one ACK from someone besides yourself and Blockchain Commons on this before merging it.

**Comment by wolfmcnally** [comment]
LGTM. If this proposal were any more complex than a simple byte string, I'd recommend it be submitted as a separate document and included here by reference, as I have done with `crypto-sskr` and the like.

**Comment by FoundationKen** [comment]
Looks good to me.  Thanks @craigraw.

**Comment by Fonta1n3** [comment]
ACK 👍 Thanks Craig.

**Review by Overtorment — APPROVED** [review]
lgtm

**Pull request merged**
